services:
  resource-service:
    container_name: resource-service
    build:
      context: ./resource-service
      dockerfile: Dockerfile
    environment:
      SPRING_DATASOURCE_URL: ${RESOURCE_DB_URL}
      SPRING_DATASOURCE_USERNAME: ${RESOURCE_DB_USER}
      SPRING_DATASOURCE_PASSWORD: ${RESOURCE_DB_PASSWORD}
      SONG_SERVICE_URL: ${SONG_SERVICE_URL}
    ports:
      - "8080:8080"
  resource-db:
    image: postgres:17-alpine3.24
    environment:
      POSTGRES_DB: ${RESOURCE_DB_NAME}
      POSTGRES_USER: ${RESOURCE_DB_USER}
      POSTGRES_PASSWORD: ${RESOURCE_DB_PASSWORD}
    ports:
      - "${RESOURCE_DB_PORT}:5432"  # Maps container port 5432 to host port 5432
    volumes:
      - ./init-scripts/resource-db:/docker-entrypoint-initdb.d
  song-service:
    container_name: song-service
    build:
      context: ./song-service
      dockerfile: Dockerfile
    environment:
      SPRING_DATASOURCE_URL: ${SONG_DB_URL}
      SPRING_DATASOURCE_USERNAME: ${SONG_DB_USER}
      SPRING_DATASOURCE_PASSWORD: ${SONG_DB_PASSWORD}
    ports:
      - "8081:8081"
  song-db:
    image: postgres:17-alpine3.24
    environment:
      POSTGRES_DB: ${SONG_DB_NAME}
      POSTGRES_USER: ${SONG_DB_USER}
      POSTGRES_PASSWORD: ${SONG_DB_PASSWORD}
    ports:
      - "${SONG_DB_PORT}:5432"  # Maps container port 5432 to host port 5433 (to avoid conflict)
    volumes:
      - ./init-scripts/song-db:/docker-entrypoint-initdb.d