spring.application.name=resource-service

#Hibernate
spring.jpa.hibernate.ddl-auto=none

# For resource-service:
spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/resource-db}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:postgres}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:postgres}

# rest
song-service.rest-api.base-url=${SONG_SERVICE_URL:http://localhost:8081}

#Eureka
eureka.client.service-url.defaultZone=${EUREKA_CLIENT_SERVICEURL_DEFAULTZONE:http://localhost:8761/eureka/}

# Frequency of heartbeats sent by the client to the server
eureka.instance.lease-renewal-interval-in-seconds=5
# Frequency of registry data retrieval from the server to the client's local cache
eureka.client.registry-fetch-interval-seconds=5

#Logging
logging.level.com.netflix.discovery.shared.resolver.aws.ConfigClusterResolver=WARN
server.tomcat.accesslog.enabled=true
server.tomcat.accesslog.directory=/dev
server.tomcat.accesslog.prefix=stdout
server.tomcat.accesslog.buffered=false
server.tomcat.accesslog.suffix=
server.tomcat.accesslog.file-date-format=
server.tomcat.accesslog.pattern=%t %a "%r" %s %b

