spring.application.name=resource-service

#Hibernate
spring.jpa.hibernate.ddl-auto=none

# For resource-service:
spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/resource-db}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:postgres}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:postgres}

# rest
song-service.rest-api.base-url=${SONG_SERVICE_URL:http://localhost:8081}

